// Package report renders the knowledge base as Markdown for people to
// read. A report is a view: it is never read back as a source.
package report

import (
	"fmt"
	"io"
	"slices"
	"strings"

	"github.com/kvitrvn/raun/internal/knowledge"
)

// Order is the order in which statuses appear within a type: settled
// knowledge first.
var Order = []knowledge.Status{
	knowledge.StatusValidated,
	knowledge.StatusNeedsReview,
	knowledge.StatusContested,
	knowledge.StatusProposed,
	knowledge.StatusRejected,
}

var typeHeadings = map[knowledge.Type]string{
	knowledge.TypePersona:     "Personas",
	knowledge.TypeRequirement: "Requirements",
}

// Render writes the items whose status is in statuses as Markdown. The
// output is deterministic (no generation date) so that committed reports
// diff cleanly.
func Render(w io.Writer, items []*knowledge.Item, statuses []knowledge.Status) error {
	var shown []*knowledge.Item
	for _, it := range items {
		if slices.Contains(statuses, it.Status) {
			shown = append(shown, it)
		}
	}
	titles := map[string]string{}
	for _, it := range items {
		titles[it.ID] = it.Title
	}

	b := &strings.Builder{}
	fmt.Fprintln(b, "# Knowledge report")
	fmt.Fprintln(b)
	fmt.Fprintf(b, "Generated by Raun from `.raun/knowledge/`. This is a view: edit the knowledge through `raun`, not here.\n\n")
	fmt.Fprintf(b, "%d item(s): %s.\n", len(shown), countByStatus(shown))

	for _, t := range knowledge.Types {
		var ofType []*knowledge.Item
		for _, status := range Order {
			for _, it := range shown {
				if it.Type == t && it.Status == status {
					ofType = append(ofType, it)
				}
			}
		}
		if len(ofType) == 0 {
			continue
		}
		fmt.Fprintf(b, "\n## %s\n", typeHeadings[t])
		for _, it := range ofType {
			renderItem(b, it, titles)
		}
	}

	_, err := io.WriteString(w, b.String())
	return err
}

func countByStatus(items []*knowledge.Item) string {
	var parts []string
	for _, status := range Order {
		n := 0
		for _, it := range items {
			if it.Status == status {
				n++
			}
		}
		if n > 0 {
			parts = append(parts, fmt.Sprintf("%d %s", n, status))
		}
	}
	if len(parts) == 0 {
		return "none"
	}
	return strings.Join(parts, ", ")
}

func renderItem(b *strings.Builder, it *knowledge.Item, titles map[string]string) {
	fmt.Fprintf(b, "\n### %s\n\n", it.Title)
	fmt.Fprintf(b, "`%s` · **%s**\n", it.ID, it.Status)

	if p := it.Persona; p != nil {
		fmt.Fprintf(b, "\n%s\n", p.Description)
		list(b, "Goals", p.Goals)
		list(b, "Capabilities", p.Capabilities)
	}
	if r := it.Requirement; r != nil {
		fmt.Fprintf(b, "\n> %s\n\n", r.Statement)
		fmt.Fprintf(b, "- Kind: %s\n", r.Kind)
		if r.Rationale != "" {
			fmt.Fprintf(b, "- Rationale: %s\n", r.Rationale)
		}
		if len(r.Personas) > 0 {
			var links []string
			for _, id := range r.Personas {
				links = append(links, fmt.Sprintf("%s (`%s`)", orUnknown(titles[id]), id))
			}
			fmt.Fprintf(b, "- Personas: %s\n", strings.Join(links, ", "))
		}
	}

	if len(it.Support) > 0 {
		fmt.Fprintf(b, "\n**Why:**\n\n")
		for _, s := range it.Support {
			fmt.Fprintf(b, "- %s (agent %s, run %s", s.Statement, s.Agent, s.Run)
			if s.Nature == knowledge.NatureHypothesis {
				b.WriteString(", hypothesis")
			}
			b.WriteString(")\n")
			for _, o := range s.Observations {
				fmt.Fprintf(b, "  - %s [%s]\n", o.Statement, strings.Join(o.Evidence, ", "))
			}
		}
	}

	if len(it.Evidence) > 0 {
		fmt.Fprintf(b, "\n**Evidence:**\n")
		for _, e := range it.Evidence {
			fmt.Fprintf(b, "\n- %s: `%s:%d-%d` at `%s` (%s, %s)\n\n", e.ID, e.Path, e.StartLine, e.EndLine, short(e.Commit), e.Source, e.State)
			fence := fenceFor(e.Excerpt)
			fmt.Fprintf(b, "  %s\n", fence)
			for line := range strings.SplitSeq(e.Excerpt, "\n") {
				fmt.Fprintf(b, "  %s\n", line)
			}
			fmt.Fprintf(b, "  %s\n", fence)
		}
	}

	if len(it.OpenPoints) > 0 {
		fmt.Fprintf(b, "\n**Open points:**\n\n")
		for _, p := range it.OpenPoints {
			state := "open"
			if !p.Unresolved() {
				state = "resolved"
			}
			by := ""
			if p.RaisedBy != "" {
				by = ", raised by " + p.RaisedBy
			}
			fmt.Fprintf(b, "- %s, %s (%s%s): %s\n", p.ID, p.Kind, state, by, p.Summary)
			for i, pos := range p.Positions {
				ev := ""
				if len(pos.Evidence) > 0 {
					ev = " [" + strings.Join(pos.Evidence, ", ") + "]"
				}
				fmt.Fprintf(b, "  %d. %s (%s)%s\n", i+1, pos.Statement, strings.Join(pos.Agents, ", "), ev)
			}
			if r := p.Resolution; r != nil {
				kept := ""
				if r.Position != nil {
					kept = fmt.Sprintf(", kept position %d", *r.Position+1)
				}
				fmt.Fprintf(b, "  - Resolved by %s on %s%s: %s\n", r.By, r.At.Format("2006-01-02"), kept, r.Note)
			}
		}
	}

	var decisions []string
	for _, e := range it.History {
		if e.Actor == knowledge.ActorHuman {
			decisions = append(decisions, fmt.Sprintf("- %s: %s -> %s by %s: %s", e.At.Format("2006-01-02"), e.From, e.To, e.By, e.Reason))
		}
	}
	if len(decisions) > 0 {
		fmt.Fprintf(b, "\n**Decisions:**\n\n%s\n", strings.Join(decisions, "\n"))
	}
}

func list(b *strings.Builder, title string, items []string) {
	if len(items) == 0 {
		return
	}
	fmt.Fprintf(b, "\n%s:\n\n", title)
	for _, s := range items {
		fmt.Fprintf(b, "- %s\n", s)
	}
}

// fenceFor returns a code fence longer than any backtick run in s.
func fenceFor(s string) string {
	longest, run := 0, 0
	for _, r := range s {
		if r == '`' {
			run++
			longest = max(longest, run)
		} else {
			run = 0
		}
	}
	return strings.Repeat("`", max(3, longest+1))
}

func short(commit string) string {
	if len(commit) > 12 {
		return commit[:12]
	}
	return commit
}

func orUnknown(title string) string {
	if title == "" {
		return "unknown persona"
	}
	return title
}
